Update README.md
tsmoyo/tsmoyo pull request #1
Opened 2021-04-26 18:30 UTC by tsmoyo

added a some details in README.md

2021-04-26 19:14 UTC, phoexer requested changes
This is ok, I left two suggestions.
So the protocol is usually when some one leaves suggestions you make changes to the branch then update the PR and re request a review. Normally we don't merge into main until you have approval, so let's try that

2021-04-26 19:14 UTC, phoexer commented on README.md
> +thabomoyo47@gmail.com)]
```suggestion
[![Gmail](mailto: thabomoyo47@gmail.com)]
```

2021-04-26 19:14 UTC, phoexer commented on README.md
> +### Hi there 👋,I'm Thabo I'm learning to build websites.
```suggestion
### Hi there 👋, I'm Thabo I'm learning to build websites.
```

2021-04-26 19:43 UTC, tsmoyo commented
how is this?

2021-04-27 07:08 UTC, phoexer approved these changes
lgtm

2021-04-27 08:04 UTC, merged